_core:
  default_config_hash: zV7uayjULNVaF8Cmo3YwtMLbB9gSkKyzC3AbsKKsK-k
langcode: en
entity_label_singular: ''
entity_label_plural: ''
cache_expiration: 900
credential_lifetime: 0
locked_base_fields:
  - displayName
required_base_fields:
  - displayName
